import { z } from "zod";

/**
 * Body accepted by POST /api/events/:eventId/access/validate.
 *
 * token          — signed QR code payload (HS256 compact token)
 * idempotencyKey — UUID generated by the scanner app at scan time.
 *                  When provided, duplicate submissions return the
 *                  original result without creating a second log entry
 *                  (supports offline Background Sync deduplication,
 *                  consistent with workload_metrics.idempotencyKey).
 * scannedAt      — client-side timestamp (ISO 8601). Stored as-is for
 *                  offline scans where server receipt time differs from
 *                  actual scan time. Defaults to server time if omitted.
 */
export const ValidateAccessSchema = z.object({
  token: z.string().min(1, "token is required"),
  idempotencyKey: z.string().uuid().optional(),
  scannedAt: z.iso.datetime().optional(),
});

export type ValidateAccessInput = z.infer<typeof ValidateAccessSchema>;

export interface ValidateAccessResponse {
  valid: boolean;
  accessLogId: string;
  reason?: string | undefined;
  scannedAt: string;
}

/**
 * Structure of the decoded QR token payload.
 * type: "field_access" — prevents confusion with member card or auth tokens.
 */
export interface QrTokenPayload {
  /** eventId embedded in the token — tamper-proof (path param alone is not enough) */
  eventId: string | null;
  /** arbitrary holder identifier (memberId, ticket number, etc.) */
  sub: string;
  type: "field_access";
  iat: number;
  exp: number;
}
